### PR TITLE
add padding to match books

### PR DESCRIPTION
**Pull request by ipinak**

### CODE REVIEW

**Comment by ArthurBeaulieu** [comment]
Hello,
Can you provide an example which this PR demonstrates its usefulness ?
Locally tested, it makes the title ribbon reduced, and doesn't span on the whole image width anymore, which is not a wanted behavior.
Kind regards.
Arthur

**Comment by ipinak** [comment]
I just changed the way it looks a bit so it match the real books. Just a few examples of this format:

- https://www.amazon.de/-/en/Julie-Steele-ebook/dp/B005QEBFKY/ref=sr_1_37?crid=24JJUJJAMW32J&dib=eyJ2IjoiMSJ9.CUQ6DvbAot6d9Bju7sNgt_H3Q73K_8BAD1lkzYgtPeNK-HLc9G2fVE0_A9GU5kIPta41Xk5zH3SQLKGw5G0h2gVLVG1k68P7lQiFjGeZjsP2_GyWG3wAsHBMY-4QB76cawpneAjG4Mjq3QLahlv86x--tp3PreNLJo-9kl46YSQ.4md1ReHcEOy7S_VyqVZ-Lj0tQFNaURwEF3I9Tah2loY&dib_tag=se&keywords=oreilly+data+engineering&qid=1727335255&sprefix=oreilly%2Caps%2C116&sr=8-37
- https://www.amazon.de/-/en/Alice-Zheng/dp/1491953241/ref=sr_1_20?crid=24JJUJJAMW32J&dib=eyJ2IjoiMSJ9.GmBB8JUMQticdtTV-ltC7T95MEPlkmbhWNhklNNdC0EW_Bqlq4Jt2r1EK9QCUdhw_v_3Ey9jLLtrJlQiNskvVg.vf_p7kAjhjvxOBL09X9XtlQPhAoFLduASPzy_ucz-HM&dib_tag=se&keywords=oreilly+data+engineering&qid=1727335237&sprefix=oreilly%2Caps%2C116&sr=8-20
- https://www.amazon.de/-/en/Laine-Campbell-ebook/dp/B076VXPXND/ref=sr_1_59?crid=24JJUJJAMW32J&dib=eyJ2IjoiMSJ9.RnrfTDUjHd7KgqrlLs4kbmlFiYlQcDluJ7PVLioOdWNaJv3cQojMFqSjvnV4O5GRPuEN_RNiacnFb9RTZ7syAEOhDPbZIxrtsmGIVERPZ2UWwY1oko1kyjyspchDJ5pId3f0Y9_I8RIoLdxdHtFQmYpXjZbmO5EMtn7Gc9flSms.LNDsEcgPdICRNw1eUNznU1aobWaKacPz4rn4QqOSSNY&dib_tag=se&keywords=oreilly+data+engineering&qid=1727335333&sprefix=oreilly%2Caps%2C116&sr=8-59

**Comment by ArthurBeaulieu** [comment]
Oh ok I see, I always thought the title ribbon took all width ; I'll try to review this to integrate with internal css vars this week or starting the next one ; thanks for the contribution tho !

**Comment by ArthurBeaulieu** [comment]
Merged and in prod, thanks ipinak
Yet, I don't know why you didn't appeared as contributor on the repo ...

**Comment by ArthurBeaulieu** [comment]
I've updated README so there is at least a trace of your contribution! Thanks

**Pull request merged**
